feat: validate imports in alembic env

diff --git a/.github/workflows/migrations.yaml b/.github/workflows/migrations.yaml
--- a/.github/workflows/migrations.yaml
+++ b/.github/workflows/migrations.yaml
@@ -16,7 +16,7 @@ jobs:
           path: "core/services"
           files: "./*/models/**"
 
-      - name: Model changes Output
+      - name: Model changes output
         env:
           CHANGED_MODEL_FILES: ${{ steps.model-changes.outputs.all_changed_files }}
         run: |
@@ -31,7 +31,7 @@ jobs:
           path: "core/alembic/versions"
           files: "*.py"
 
-      - name: Migration changes Output
+      - name: Migration changes output
         env:
           CHANGED_MIGRATION_FILES: ${{ steps.migration-changes.outputs.all_changed_files }}
         run: |
@@ -58,6 +58,7 @@ jobs:
     
     outputs:
       changed_migration_files: ${{ steps.migration-changes.outputs.all_changed_files }}
+      changed_model_file: ${{ steps.model-changes.outputs.all_changed_files }}
 
     
   prevent-changes:
@@ -82,6 +83,35 @@ jobs:
             fi
           done
   
+  check-missing-imports:
+    runs-on: ubuntu-latest
+    needs: detect-diffs
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Check for Missing imports in alembic
+        id: missing-imports
+        run: |
+          CHANGED_MODEL_FILES="${{ needs.detect-diffs.outputs.changed_model_files }}"
+
+          IMPORTS=$(grep -oP "from services\.\w+\.models\.\w+ import \w+" core/alembic/env.py)
+          MISSING_IMPORTS=()
+
+          for line in $CHANGED_MODEL_FILES; do
+            model_name=$(basename "$model" .py)
+
+            # Is the model somewhere in the imports?
+            if ! echo "$IMPORTS" | grep -q "$model_name"; then
+              MISSING_IMPORTS+=("$model_name")
+            fi
+          done
+
+          if [ ${#MISSING_IMPORTS[@]} -ne 0 ]; then
+            echo "You probably forget to import follwoing models within the alembic/env file: ${MISSING_IMPORTS[*]}"
+            exit 1
+          fi 
+
   check-migrations:
     runs-on: ubuntu-latest
     needs: prevent-changes
@@ -120,12 +150,13 @@ jobs:
         run: |
           echo "DATABASE_HOST=localhost" >> .env
       
-      - name: Run Migrations
+      - name: Run Migrations UP
         working-directory: ./core
         run: alembic upgrade head
-
-      - name: Check Migrations
+      
+      - name: Run Migrations DOWN
         working-directory: ./core
-        run: alembic check
+        run: alembic downgrade base
 
 
+# CASE 2: Forgot running alembic revision -m test
